{{- range $i := until (.Values.worker.node_count | int) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.cluster_name }}-worker-{{ $i }}-cloudinit
  namespace: {{ $.Values.cluster_namespace }}
stringData:
  userdata: |
    #cloud-config
    {{- if $.Values.vm.qemu_agent_install }}
    package_update: true
    packages:
      - qemu-guest-agent
    {{- end }}
    write_files: 
    - path: /etc/rancher/rke2/config.yaml
      owner: root
      content: |
        token: {{ $.Values.shared_token }}
        {{- if ne $i 0 }}
        server: https://{{ $.Values.control_plane.vip }}:9345
        {{- end }}
        system-default-registry: {{ $.Values.system_default_registry }}
        secrets-encryption: true
        write-kubeconfig-mode: 0640
        use-service-account-credentials: true
    - path: /etc/hosts
      owner: root
      content: |
        127.0.0.1 localhost
        127.0.0.1 {{$.Values.cluster_name }}-worker-{{ $i }}
    runcmd:
    {{- if $.Values.vm.qemu_agent_enable }}
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
    {{- end }}
    {{- if not $.Values.vm.airgapped_image }}
    - mkdir -p /var/lib/rancher/rke2-artifacts && wget https://get.rke2.io -O /var/lib/rancher/install.sh && chmod +x /var/lib/rancher/install.sh
    {{- end}}
    - INSTALL_RKE2_VERSION={{ $.Values.rke2_version }} INSTALL_RKE2_TYPE="agent" /var/lib/rancher/install.sh
    - systemctl enable rke2-server.service
    - systemctl start rke2-server.service
    ssh_authorized_keys: 
    - {{ $.Values.ssh_pub_key }}
{{- end}}