---
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: {{ $.Values.cluster_name }}-pool
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  ranges:
    - gateway: 10.10.0.1
      rangeEnd: 10.10.0.5
      rangeStart: 10.10.0.5
      subnet: 10.10.0.0/24
  selector: {}
---
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: LoadBalancer
metadata:
  name: {{ .Values.cluster_name }}-lb
  namespace: default
  annotations: 
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  healthCheck:
    failureThreshold: 2
    port: 6443
    successThreshold: 3
    timeoutSeconds: 5
    periodSeconds: 5
  ipam: pool
  ipPool: {{ .Values.cluster_name }}-pool
  listeners:
    - name: k8s-api
      port: 6443
      protocol: TCP
      backendPort: 6443
    - name: ingress
      port: 443
      protocol: TCP
      backendPort: 443
    - name: join
      port: 9345
      protocol: TCP
      backendPort: 9345
  workloadType: vm
  backendServerSelector:
    harvesterhci.io/vmName:
    {{- range $i := until (.Values.control_plane.node_count | int)}}
    - {{ $.Values.cluster_name }}-cp-{{ $i }}
    {{- end}}